//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Asset struct {
	ID            int64 `sql:"primary_key"`
	WorkspaceID   int64
	UserID        int64
	Name          string
	Icon          string
	OriginalValue float64
	CurrentValue  float64
	AcquiredAt    time.Time
}
