//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Currency struct {
	Code         string `sql:"primary_key"`
	Symbol       string
	ExchangeRate float64
	LastUpdated  *time.Time
}
