//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type EnvelopeAllocation struct {
	ID            int64 `sql:"primary_key"`
	MonthNotation int32
	TemplateID    *int64
	Amount        float64
	Utilized      float64
}
