//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type EnvelopeTemplate struct {
	ID         int64 `sql:"primary_key"`
	EnvelopeID int64
	CategoryID int64
	Amount     float64
	Active     bool
}
