//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type LoanRepayment struct {
	ID            int64 `sql:"primary_key"`
	WorkspaceID   int64
	TransactionID int64
	UserID        int64
	PrincipalPaid float64
	InterestPaid  float64
}
