//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type LoanStatus string

const (
	LoanStatus_Active    LoanStatus = "active"
	LoanStatus_Cancelled LoanStatus = "cancelled"
	LoanStatus_Paid      LoanStatus = "paid"
)

func (e *LoanStatus) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "active":
		*e = LoanStatus_Active
	case "cancelled":
		*e = LoanStatus_Cancelled
	case "paid":
		*e = LoanStatus_Paid
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for LoanStatus enum")
	}

	return nil
}

func (e LoanStatus) String() string {
	return string(e)
}
