//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type Meta struct {
	Key   string `sql:"primary_key"`
	Value *string
}
