//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type PgStatKcache struct {
	Datname        *string
	PlanUserTime   *float64
	PlanSystemTime *float64
	PlanMinflts    *float64
	PlanMajflts    *float64
	PlanNswaps     *float64
	PlanReads      *float64
	PlanReadsBlks  *float64
	PlanWrites     *float64
	PlanWritesBlks *float64
	PlanMsgsnds    *float64
	PlanMsgrcvs    *float64
	PlanNsignals   *float64
	PlanNvcsws     *float64
	PlanNivcsws    *float64
	ExecUserTime   *float64
	ExecSystemTime *float64
	ExecMinflts    *float64
	ExecMajflts    *float64
	ExecNswaps     *float64
	ExecReads      *float64
	ExecReadsBlks  *float64
	ExecWrites     *float64
	ExecWritesBlks *float64
	ExecMsgsnds    *float64
	ExecMsgrcvs    *float64
	ExecNsignals   *float64
	ExecNvcsws     *float64
	ExecNivcsws    *float64
}
