//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type PgStatKcacheDetail struct {
	Query          *string
	Top            *bool
	Datname        *string
	Rolname        *string
	PlanUserTime   *float64
	PlanSystemTime *float64
	PlanMinflts    *int64
	PlanMajflts    *int64
	PlanNswaps     *int64
	PlanReads      *int64
	PlanReadsBlks  *int64
	PlanWrites     *int64
	PlanWritesBlks *int64
	PlanMsgsnds    *int64
	PlanMsgrcvs    *int64
	PlanNsignals   *int64
	PlanNvcsws     *int64
	PlanNivcsws    *int64
	ExecUserTime   *float64
	ExecSystemTime *float64
	ExecMinflts    *int64
	ExecMajflts    *int64
	ExecNswaps     *int64
	ExecReads      *int64
	ExecReadsBlks  *int64
	ExecWrites     *int64
	ExecWritesBlks *int64
	ExecMsgsnds    *int64
	ExecMsgrcvs    *int64
	ExecNsignals   *int64
	ExecNvcsws     *int64
	ExecNivcsws    *int64
}
