//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type PgStatStatements struct {
	Userid               *string
	Dbid                 *string
	Toplevel             *bool
	Queryid              *int64
	Query                *string
	Plans                *int64
	TotalPlanTime        *float64
	MinPlanTime          *float64
	MaxPlanTime          *float64
	MeanPlanTime         *float64
	StddevPlanTime       *float64
	Calls                *int64
	TotalExecTime        *float64
	MinExecTime          *float64
	MaxExecTime          *float64
	MeanExecTime         *float64
	StddevExecTime       *float64
	Rows                 *int64
	SharedBlksHit        *int64
	SharedBlksRead       *int64
	SharedBlksDirtied    *int64
	SharedBlksWritten    *int64
	LocalBlksHit         *int64
	LocalBlksRead        *int64
	LocalBlksDirtied     *int64
	LocalBlksWritten     *int64
	TempBlksRead         *int64
	TempBlksWritten      *int64
	BlkReadTime          *float64
	BlkWriteTime         *float64
	TempBlkReadTime      *float64
	TempBlkWriteTime     *float64
	WalRecords           *int64
	WalFpi               *int64
	WalBytes             *float64
	JitFunctions         *int64
	JitGenerationTime    *float64
	JitInliningCount     *int64
	JitInliningTime      *float64
	JitOptimizationCount *int64
	JitOptimizationTime  *float64
	JitEmissionCount     *int64
	JitEmissionTime      *float64
}
