//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type RecurringTransaction struct {
	ID             int64 `sql:"primary_key"`
	CategoryID     int64
	UserID         int64
	Amount         float64
	FromID         int64
	ToID           int64
	Source         TransactionSource
	Dest           TransactionSource
	Frequency      TransactionFrequency
	NextOccurrence *time.Time
}
