//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var GoalStatus = &struct {
	Active    postgres.StringExpression
	Completed postgres.StringExpression
	Failed    postgres.StringExpression
}{
	Active:    postgres.NewEnumValue("active"),
	Completed: postgres.NewEnumValue("completed"),
	Failed:    postgres.NewEnumValue("failed"),
}
