//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var RecurringType = &struct {
	Subscription postgres.StringExpression
	Bills        postgres.StringExpression
	Income       postgres.StringExpression
	Expense      postgres.StringExpression
}{
	Subscription: postgres.NewEnumValue("subscription"),
	Bills:        postgres.NewEnumValue("bills"),
	Income:       postgres.NewEnumValue("income"),
	Expense:      postgres.NewEnumValue("expense"),
}
