//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var Role = &struct {
	Owner     postgres.StringExpression
	Read      postgres.StringExpression
	ReadWrite postgres.StringExpression
	None      postgres.StringExpression
}{
	Owner:     postgres.NewEnumValue("owner"),
	Read:      postgres.NewEnumValue("read"),
	ReadWrite: postgres.NewEnumValue("read_write"),
	None:      postgres.NewEnumValue("none"),
}
