//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var TransactionFrequency = &struct {
	Daily   postgres.StringExpression
	Weekly  postgres.StringExpression
	Monthly postgres.StringExpression
	Yearly  postgres.StringExpression
	Manual  postgres.StringExpression
}{
	Daily:   postgres.NewEnumValue("daily"),
	Weekly:  postgres.NewEnumValue("weekly"),
	Monthly: postgres.NewEnumValue("monthly"),
	Yearly:  postgres.NewEnumValue("yearly"),
	Manual:  postgres.NewEnumValue("manual"),
}
