//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

// UseSchema sets a new schema name for all generated table SQL builder types. It is recommended to invoke
// this method only once at the beginning of the program.
func UseSchema(schema string) {
	Asset = Asset.FromSchema(schema)
	Category = Category.FromSchema(schema)
	CreditCardAccount = CreditCardAccount.FromSchema(schema)
	Currency = Currency.FromSchema(schema)
	DepositAccount = DepositAccount.FromSchema(schema)
	Envelope = Envelope.FromSchema(schema)
	EnvelopeAllocation = EnvelopeAllocation.FromSchema(schema)
	EnvelopeTemplate = EnvelopeTemplate.FromSchema(schema)
	ExternalEntity = ExternalEntity.FromSchema(schema)
	FileUpload = FileUpload.FromSchema(schema)
	Goal = Goal.FromSchema(schema)
	GoalDistribution = GoalDistribution.FromSchema(schema)
	GooseDbVersion = GooseDbVersion.FromSchema(schema)
	Loan = Loan.FromSchema(schema)
	LoanRepayment = LoanRepayment.FromSchema(schema)
	Market = Market.FromSchema(schema)
	Meta = Meta.FromSchema(schema)
	RecurringTransaction = RecurringTransaction.FromSchema(schema)
	Security = Security.FromSchema(schema)
	SecurityAccount = SecurityAccount.FromSchema(schema)
	SecurityItem = SecurityItem.FromSchema(schema)
	Tag = Tag.FromSchema(schema)
	Transaction = Transaction.FromSchema(schema)
	User = User.FromSchema(schema)
	Workspace = Workspace.FromSchema(schema)
	WorkspaceAccess = WorkspaceAccess.FromSchema(schema)
}
