//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var WorkspaceAccess = newWorkspaceAccessTable("public", "workspace_access", "")

type workspaceAccessTable struct {
	postgres.Table

	// Columns
	WorkspaceID postgres.ColumnInteger
	UserID      postgres.ColumnInteger
	Role        postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type WorkspaceAccessTable struct {
	workspaceAccessTable

	EXCLUDED workspaceAccessTable
}

// AS creates new WorkspaceAccessTable with assigned alias
func (a WorkspaceAccessTable) AS(alias string) *WorkspaceAccessTable {
	return newWorkspaceAccessTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new WorkspaceAccessTable with assigned schema name
func (a WorkspaceAccessTable) FromSchema(schemaName string) *WorkspaceAccessTable {
	return newWorkspaceAccessTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new WorkspaceAccessTable with assigned table prefix
func (a WorkspaceAccessTable) WithPrefix(prefix string) *WorkspaceAccessTable {
	return newWorkspaceAccessTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new WorkspaceAccessTable with assigned table suffix
func (a WorkspaceAccessTable) WithSuffix(suffix string) *WorkspaceAccessTable {
	return newWorkspaceAccessTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newWorkspaceAccessTable(schemaName, tableName, alias string) *WorkspaceAccessTable {
	return &WorkspaceAccessTable{
		workspaceAccessTable: newWorkspaceAccessTableImpl(schemaName, tableName, alias),
		EXCLUDED:             newWorkspaceAccessTableImpl("", "excluded", ""),
	}
}

func newWorkspaceAccessTableImpl(schemaName, tableName, alias string) workspaceAccessTable {
	var (
		WorkspaceIDColumn = postgres.IntegerColumn("workspace_id")
		UserIDColumn      = postgres.IntegerColumn("user_id")
		RoleColumn        = postgres.StringColumn("role")
		allColumns        = postgres.ColumnList{WorkspaceIDColumn, UserIDColumn, RoleColumn}
		mutableColumns    = postgres.ColumnList{RoleColumn}
	)

	return workspaceAccessTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		WorkspaceID: WorkspaceIDColumn,
		UserID:      UserIDColumn,
		Role:        RoleColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
